KT-8-2
koteev-m/KotlinTasksV4 pull request #20
Opened 2024-07-29 11:43 UTC by koteev-m

2024-07-30 05:50 UTC, ievetrovdev requested changes

2024-07-30 05:50 UTC, ievetrovdev commented on src/main/kotlin/arrays/task_8_2.kt
> +//Представь, что ты работаешь над приложением с рецептами.
Комментарии, не относящиеся к решению или не несущие никакой полезной нагрузки для будущего себя или других разработчиков в команде – лучше не оставлять в продакшн коде.

2024-07-30 05:50 UTC, ievetrovdev commented on src/main/kotlin/arrays/task_8_2.kt
> +    for (ingredient in ingredients){
По коду все корректно)

2024-07-31 13:34 UTC, koteev-m commented on src/main/kotlin/arrays/task_8_2.kt
> +    for (ingredient in ingredients){
ни чего не менял. Вы мне разрешили оставить комменты

2024-08-01 09:31 UTC, ievetrovdev approved these changes

2024-08-01 12:16 UTC, merged