KT-8-3
koteev-m/KotlinTasksV4 pull request #21
Opened 2024-07-29 11:45 UTC by koteev-m

2024-07-30 05:52 UTC, ievetrovdev requested changes

2024-07-30 05:52 UTC, ievetrovdev commented on src/main/kotlin/arrays/task_8_3.kt
> +    if (ingredients.contains(inputIngredient)){
Еще аккуратнее будет выглядеть, если проверять наличие элемента ключевым словом `in`

2024-07-30 05:52 UTC, ievetrovdev commented on src/main/kotlin/arrays/task_8_3.kt
> +//Используй условие из предыдущей задачи. Нужно доработать код, который проверяет наличие ингредиента в рецепте.
Давай также почистим комментарии

2024-07-31 13:34 UTC, koteev-m commented on src/main/kotlin/arrays/task_8_3.kt
> +//Используй условие из предыдущей задачи. Нужно доработать код, который проверяет наличие ингредиента в рецепте.
ни чего не менял. Вы мне разрешили оставить комменты

2024-08-01 09:31 UTC, ievetrovdev approved these changes

2024-08-01 12:16 UTC, merged